version: "3"

networks:
  tier_1: { }
  tier_2: { }
  tier_3: { }

services:
  tier_1:
    build:
      context: ./tier_1
    networks:
      - tier_1
      - tier_2
    restart: unless-stopped
    environment:
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      # public facing site
      - '8000:8000'
      # admin
      - '8001:8001'

  tier_2:
    build:
      context: ./tier_2
    networks:
      - tier_1
      - tier_2
    restart: unless-stopped

  tier_3:
    build:
      context: ./tier_3
    networks:
      - tier_3
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    restart: unless-stopped
