version: "3"

networks:
  tier_1: { }
  tier_2: { }
  tier_3: { }

services:
  kong_database:
    image: postgres:9.6-alpine
    networks:
      - tier_1
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=kong
    restart: unless-stopped

  kong_net:
    image: kong:2.1.4-alpine
    build:
      context: ./tier_1
    networks:
      - tier_1
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong_database
      - KONG_PG_USER=admin
      - KONG_PG_PASSWORD=admin
    command: /bin/bash -c 'kong migrations bootstrap'

  kong:
    build:
      context: ./tier_1
    networks:
      - tier_1
    restart: unless-stopped
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong_database
      - KONG_PG_USER=admin
      - KONG_PG_PASSWORD=admin

      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - '8000:8000'
      - '8443:8443'
      - '8001:8001'
      - '8444:8444'

  tier_2:
    build:
      context: ./tier_2
    networks:
      - tier_1
      - tier_2
    restart: unless-stopped

  tier_3:
    build:
      context: ./tier_3
    networks:
      - tier_3
    restart: unless-stopped
